# Generated by Django 3.2.4 on 2021-07-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=200, null=True)),
                ('AvgBookRating', models.CharField(max_length=200, null=True)),
                ('NumberOfRating', models.CharField(max_length=200, null=True)),
                ('BookTitle', models.CharField(max_length=200, null=True)),
                ('BookAuthor', models.CharField(max_length=200, null=True)),
                ('YearOfPublication', models.CharField(max_length=200, null=True)),
                ('Publisher', models.CharField(max_length=200, null=True)),
                ('new_score', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('Genre', models.CharField(max_length=200, null=True)),
                ('Previewlink', models.CharField(max_length=200, null=True)),
                ('Image', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
