# Generated by Django 3.2.4 on 2021-07-14 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='AvgBookRating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='new_score',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(through='books.Favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
