# Generated by Django 3.2.4 on 2021-07-14 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_auto_20210714_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'readbook')},
            },
        ),
    ]
