# Generated by Django 3.2.4 on 2021-07-31 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_auto_20210731_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='readlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
